name: Integration tests
on: [push, pull_request]
jobs:
  build:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install mage
        run: "pushd /tmp; git clone https://github.com/magefile/mage; pushd mage; go run bootstrap.go; popd; popd"

      - name: Install Protobuf compiler
        uses: arduino/setup-protoc@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Protobuf Go plugin
        run: |
          go get github.com/golang/protobuf/protoc-gen-go

      - name: Check out bitcoin-svc
        uses: actions/checkout@master
        with:
          repository: LedgerHQ/bitcoin-svc
          path: 'bitcoin-svc'

      - name: Run bitcoin-svc in the background
        run: |
          pushd bitcoin-svc
          mage -v build
          ./lbs &
          popd

      - name: Build
        run: |
          mage -v build

      - name: Run integration tests
        run: mage -v integration
